apiVersion: v1
kind: Namespace
metadata:
  name: tuheg-production
  labels:
    name: tuheg-production
    environment: production
    project: tuheg
---
apiVersion: v1
kind: Namespace
metadata:
  name: tuheg-staging
  labels:
    name: tuheg-staging
    environment: staging
    project: tuheg
